/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {
    public static void main(String[] args) throws Throwable {
        String list = Nexus2HttpClient.listFetch();
        PerseSearchXML perser = new PerseSearchXML(list);
        perser.getBaseValue(context -> {
            if ("module".equals(context.extension())) {
                System.out.println("----------------------");
                System.out.println(
                        "Artifact found: " + context.groupId() + ":" + context.artifactId() + ":" + context.version());

                // Fetch the POM file and extract kind and qname from properties
                String pomUrl = context.groupId().replace(".", "/")
                        + "/" + context.artifactId()
                        + "/" + context.version()
                        + "/" + context.artifactId() + "-" + context.version() + ".pom";
                try {
                    String pomContent = Nexus2HttpClient.pomFetch(pomUrl);
                    PersePomXML perserPom = new PersePomXML(pomContent);

                    System.out.println(context.groupId());
                    System.out.println(context.artifactId());
                    System.out.println(context.version());
                    System.out.println(context.extension());
                    System.out.println(perserPom.getKind());
                    System.out.println(perserPom.getQName());
                } catch (Exception e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

    }
}
